---
functional:
    # 1
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
    # 2
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
    # 3
  - Пользователь должен иметь возможность фильтровать товары
    # 4
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
    # 5
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
    # 6
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы 
    # 7
  - Сайт должен иметь мобильную версию
    # 8
  - Сайт должен быть доступен на различных устройствах
    # 9
  - Сайт нужно протестировать на совместимость с последними версиями браузеров 
    # 10
  - Важно, чтобы сайт мог обрабатывать большое количество трафика  
    # 11
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
    # 12
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  # Функциональные требования
    # 13
  - Должен быть организован постраничный вывод товаров (пагинация) с выводом номера страниц и навигацией
    # 14
  - На странице со списоком товаров, для каждого товара должно отображаться изображение, наименование и цена
    # 15
  - Товар, отсутствующий на складе, должен быть помечен на главной странице и в карточке, как "нет в наличии" и не должен добавляться в корзину
    # 16
  - В карточке товара должна отображаться подробная информация о товаре, включая - изображение, наименование, категорию, рейтинг продаж, цену, описание и наличие на складе
    # 17
  - Фильтрация должна быть доступна при выводе списка товаров по всем категориям, по всем производителям по всему диапазону цен товаров и по наличию на складе
    # 18
  - Фильтры должны поддерживать множественный выбор
    # 19
  - Должна быть возможность сброса установленных фильтров
    # 20
  - Должна быть возможность сортировки товаров по цене (по возрастанию и по убыванию), по популярности и по рейтингу
    # 21
  - В корзине должна быть возможность изменять количество товаров и удалять товары из корзины
    # 22
  - Установленные фильтры должны сохраняться при переходе между страницами списка товаров и при возврате на страницу списка товаров
    # 23
  - Количество товара в корзине не должно превышать доступного на складе или быть отрицательным
    # 24
  - Должна быть возможность очистки корзины
    # 25
  - Должна быть возможность оформления заказа с указанием контактной информации и адреса доставки
    # 26
  - После оформления заказа должна отображаться страница с подтверждением заказа и его деталями
    # 27`
  - В корзине должны отображаться наименование товара, цена за единицу, количество и общая стоимость
    # 28
  - Содержимое корзины должно сохраняться  при обновлении страницы, перреходе в другой раздел сайта или при закрытии браузера
    # 29
  - Содержимое корзины должно очищаться после успешного оформления заказа
    # 30
  - Заказы должны быть сохранены в базе данных
    # 31
  - Пользователь должен иметь возможность просматривать статус и историю своих заказов
    # 32
  - Пользователь должен получать уведомление об успешном оформлении заказа
  # Безопасность и защита данных пользователя
    # 33
  - Для совершения покупок пользователь должен быть авторизован
    # 34
  - На сайте должна быть реализована регистрация новых пользователей
    # 35
  - При регистрации нового пользователя должен быть указан номер телефона и/или адрес электронной почты
    # 36
  - Пароли пользователей должны храниться в базе данных в зашифрованном виде
    # 37
  - Должна быть возможность смены и восстановления пароля, смены номера телефона и адреса электронной почты
    # 38
  - Должна быть возможность удаления аккаунта пользователя
    # 39
  - Сайт должен использовать HTTPS для защиты данных пользователя
    # 40
  - Доступ к личным данным пользователя должен быть ограничен
  # usability
    # 41
  - Переключатель языка интерфейса должен быть доступен всегда
    # 42
  - Рядом с переключателем языка должна отображаться информация о текущем языке интерфейса
    # 43
  - Выбранный язык интерфейса должен сохраняться при переходе между страницами сайта
    # 44
  - Все кнопки должны иметь подписи
    # 45
  - Все чек-боксы и радиокнопки должны иметь подписи
    # 46
  - Все поля ввода должны иметь подписи и подсказки
    # 47
  - Все обязательные поля должны быть помечены
    # 48
  - Вся обображаемая информация должна быть понятной и легко читаемой
  # Адаптивность и кросс-браузерность
    # 49
  - Статические элементы интерфейса не должны перекрывать друг друга при изменении размеров окна браузера и на различных устройствах
    # 50
  - Все элементы интерфейса должны быть доступны и функциональны на различных устройствах (десктоп, планшет, мобильный телефон)
    # 51
  - Выводимые изображения не должны быть искажены
  # Интерфейс и дизайн
    # 52
  - Цветовая схема сайта должна обеспечивать достаточный контраст между текстом и фоном
    # 53
  - Шрифты должны быть легко читаемыми и иметь достаточный размер
    # 54
  - При наведении мыши на интерактивные элементы интерфейса должен меняться указатель мыши
  # Производительность
    # 55
  - Изображения должны быть оптимизированы для быстрой загрузки
    # 56
  - Время загрузки главной страницы не должно первышать 2 секунд при среднем качестве соединения
    # 57
  - Время отклика при нажатии на кнопки и ссылки не должно первышать 1 секунду
    # 58
  - Сайт должен обеспечивать стабильную работу при одновременном посещении 1000 пользователей
  