---
functional:
    # RC1
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
    # RC2
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
    # RC3
  - Пользователь должен иметь возможность фильтровать товары
    # RC4
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
    # RC5
  - Пользователь должен иметь возможность переключить язык интерфейса
    # RC13+++
  - Должен быть организован постраничный вывод товаров (пагинация) с выводом номера страниц и навигацией
    # RC21+++
  - В корзине должна быть возможность изменять количество товаров и удалять товары из корзины
    # RC25+++
  - Должна быть возможность оформления заказа с указанием контактной информации и адреса доставки
    # RC28+++
  - Содержимое корзины должно сохраняться  при обновлении страницы, переходе в другой раздел сайта или при закрытии браузера
    # RC14+++
  - На странице со списоком товаров, для каждого товара должно отображаться изображение, наименование, рейтинг продаж и цена со скидкой и без скидки
    # RC16+++
  - В карточке товара должна отображаться подробная информация о товаре, включая - изображение, наименование, категорию, рейтинг продаж, цену, описание и наличие на складе
    # RC57+++
  - Для выбора способа оплаты и совершения покупки пользователем, должна быть страница оплаты товара
non-functional:
    # RC6
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы 
    # RC7
  - Сайт должен иметь мобильную версию
    # RC8
  - Сайт должен быть доступен на различных устройствах
    # RC9
  - Сайт нужно протестировать на совместимость с последними версиями браузеров 
    # RC10
  - Важно, чтобы сайт мог обрабатывать большое количество трафика  
    # RC11
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
    # RC12
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  # Функциональные требования
    # RC15
  - Товар, отсутствующий на складе, должен быть помечен на главной странице и в карточке, как "нет в наличии" и не должен добавляться в корзину
    # RC17
  - Фильтрация должна быть доступна при выводе списка товаров по всем категориям, по всем производителям по всему диапазону цен товаров и по наличию на складе
    # RC18
  - Фильтры должны поддерживать множественный выбор
    # RC19
  - Должна быть возможность сброса установленных фильтров
    # RC20
  - Должна быть возможность сортировки товаров по цене (по возрастанию и по убыванию), по популярности и по рейтингу
    # RC22
  - Установленные фильтры должны сохраняться при переходе между страницами списка товаров и при возврате на страницу списка товаров из корзины
    # RC23
  - Количество товара в корзине не должно превышать доступного на складе или быть отрицательным
    # RC24
  - Должна быть возможность очистки корзины
    # RC26
  - После оформления заказа должна отображаться страница с подтверждением заказа и его деталями
    # RC27
  - В корзине должны отображаться наименование товара, цена за единицу, количество и общая стоимость
    # RC29
  - Содержимое корзины должно очищаться после успешного оформления заказа
    # RC30
  - Заказы должны быть сохранены в базе данных
    # RC31
  - Пользователь должен иметь возможность просматривать статус и историю своих заказов
    # RC32
  - Пользователь должен получать уведомление об успешном оформлении заказа
  # Безопасность и защита данных пользователя
    # RC33!!!
  - Для совершения покупок пользователь должен быть авторизован
    # RC34
  - На сайте должна быть реализована регистрация новых пользователей
    # RC35
  - При регистрации нового пользователя должен быть указан номер телефона и/или адрес электронной почты
    # RC36
  - Пароли пользователей и контактная информация должны храниться в базе данных в зашифрованном виде
    # RC37
  - Должна быть возможность смены и восстановления пароля, смены номера телефона и адреса электронной почты
    # RC38
  - Должна быть возможность удаления аккаунта пользователя
    # RC39
  - Сайт должен использовать HTTPS для защиты данных пользователя
    # RC40
  - Доступ к личным данным пользователя должен быть ограничен
  # usability
    # RC41
  - Переключатель языка интерфейса должен быть доступен всегда
    # RC42---
    #- Рядом с переключателем языка должна отображаться информация о текущем языке интерфейса
    # RC43---
    #- Выбранный язык интерфейса должен сохраняться при переходе между страницами сайта
    # RC44
  - Все элементы интерфейса должны иметь подписи или подсказки
    # RC45
  - Все обязательные для заполнения поля должны быть помечены
    # RC46
  - Вся обображаемая информация должна быть понятной и легко читаемой
  # Адаптивность и кросс-браузерность
    # RC47
  - Статические элементы интерфейса не должны перекрывать друг друга при изменении размеров окна браузера и на различных устройствах
    # RC48
  - Все элементы интерфейса должны быть доступны и функциональны на различных устройствах (десктоп, планшет, мобильный телефон)
    # RC49+++
  - Выводимые изображения должны быть чёткими и без искажений, на различных устройствах (десктоп, планшет, мобильный телефон)
  # Интерфейс и дизайн
    # RC50
  - Цветовая схема сайта должна обеспечивать достаточный контраст между текстом и фоном
    # RC51
  - Шрифты должны быть легко читаемыми и иметь достаточный размер
    # RC52
  - При наведении мыши на интерактивные элементы интерфейса должен меняться указатель мыши
  # Производительность
    # RC53
  - Изображения должны быть оптимизированы для быстрой загрузки
    # RC54
  - Время загрузки главной страницы не должно первышать 2 секунд при среднем качестве соединения
    # RC55
  - Время отклика при нажатии на кнопки и ссылки не должно первышать 1 секунду
    # RC56
  - Сайт должен обеспечивать стабильную работу при одновременном посещении 100 пользователей
  