---
functional:
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров 
  - Важно, чтобы сайт мог обрабатывать большое количество трафика  
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  # Функциональные требования
  - На главной странице должен отображаться список товаров с изображением, наименованием и ценой
  - При выборе товара должна открываться карточка товара с подробной информацией
  - Товар, отсутствующий на складе, должен быть помечен на главной странице и в карточке, как "нет в наличии" и не должен добавляться в корзину
  - Должны быть фильтры по категории товара, по производителю, по цене и по наличию на складе
  - В корзине, должно быть реализовано удаление и изменение количества товаров
  - Количество товара в корзине не должно превышать доступного на складе или быть отрицательным
  - В корзине должны отображаться наименование товара, цена за единицу, количество и общая стоимость
  - Содержимое корзины должно сохраняться  при обновлении страницы, перреходе в другой раздел сайта или при закрытии браузера
  - Содержимое корзины должно очищаться после успешного оформления заказа
  - Заказы должны быть сохранены в базе данных
  - Пользователь должен иметь возможность просматривать статус и историю своих заказов
  - Пользователь должен получать уведомление об успешном оформлении заказа
  # Безопасность и защита данных пользователя
  - Для совершения покупок пользователь должен быть авторизован
  - На сайте должна быть реализована регистрация новых пользователей
  - При регистрации нового пользователя должен быть указан номер телефона и/или адрес электронной почты
  - Должна быть возможность смены и восстановления пароля, смены номера телефона и адреса электронной почты
  - Должна быть возможность удаления аккаунта пользователя
  - Сайт должен использовать HTTPS для защиты данных пользователя
  - Доступ к личным данным пользователя должен быть ограничен
  # usability
  - Переключатель языка интерфейса должен быть доступен всегда
  - Рядом с переключателем языка должна отображаться информация о текущем языке интерфейса
  - Все кнопки должны иметь подписи
  - Все чек-боксы и радиокнопки должны иметь подписи
  - Все поля ввода должны иметь подписи и подсказки
  - Все обязательные поля должны быть помечены
  - Вся обображаемая информация должна быть понятной и легко читаемой
  - Статические элементы интерфейса не должны перекрывать друг друга при изменении размеров окна браузера и на различных устройствах
  - Выводимые изображения не должны быть искажены
  - При наведении мыши на интерактивные элементы интерфейса должен меняться указатель мыши
  # Производительность
  - Изображения должны быть оптимизированы для быстрой загрузки
  - Время загрузки главной страницы не должно первышать 2 секунд при среднем качестве соединения
  - Время отклика при нажатии на кнопки и ссылки не должно первышать 1 секунду
  - Сайт должен обеспечивать стабильную работу при одновременном посещении 1000 пользователей
  